# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a0c6da9a47ef585b88e7188f3a857ad2db1643e868f42f3a31779dd99b88b8ae340f402ba2d590800d2f1a51b8863ce797ddf97cb51537890299f2ebf7e2022

test:
  secret_key_base: ff16b15a481916e2fbc09bbeafc410af5edd828638916f6f80c731f7dd265f49a842dfeb4ea0c6900c7b0874da7afdece9d74c9f54f6b69fabf1f5cfb7fd1aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
